#lang racket
(require "match.rkt")
(define (forall? pred lst)
  (cond ((null? lst) #t)
        ((pred (car lst))
         (forall? pred (cdr lst)))
        (else #f)))
(define (exists? pred lst)
  (cond ((null? lst) #f)
        ((pred (car lst)) #t)
        (else
         (exists? pred (cdr lst)))))
(define (fold-left proc init lst)
  (if (null? lst)
      init
      (fold-left proc (proc init (car lst)) (cdr lst))))
(define (remove-all x lst)
  (cond ((null? lst) '())
        ((equal? x (car lst))
         (remove-all x (cdr lst)))
        (else
         (cons (car lst) (remove-all x (cdr lst))))))
;set operations
(define (set-cons x s)
  (if (member x s)
      s
      (cons x s)))
(define (setlize x*)
  (if (null? x*)
      '()
      (set-cons (car x*)
                (setlize (cdr x*)))))
(define (U s1 s2)
  (cond ((null? s1) s2)
        ((member (car s1) s2) (U (cdr s1) s2))
        (else (cons (car s1) (U (cdr s1) s2)))))
(define U*
  (case-lambda
    (() '())
    ((s) s)
    ((s1 s2 . s*) (apply U* (U s1 s2) s*))))
(define (D s1 s2)
  (cond ((null? s1) '())
        ((member (car s1) s2) (D (cdr s1) s2))
        (else (cons (car s1) (D (cdr s1) s2)))))
(define (I? s1 s2)
  (cond ((null? s1) #f)
        ((member (car s1) s2) #t)
        (else (I? (cdr s1) s2))))
(define (subset? s1 s2)
  (cond ((null? s1) #t)
        ((member (car s1) s2)
         (subset? (cdr s1) s2))
        (else #f)))
;<exp> ::= <bool>
;       |  <var>
;       |  (not <exp>)
;       |  (and <exp> <exp>)
;       |  (or <exp> <exp>)
;       |  (=> <exp> <exp>)
;       |  (<=> <exp> <exp>)
(define peirce
  '(=> (=> (=> p q) p) p))
(define p<=>q<=>r
  '(<=> p (<=> q r)))
(define (ev e v)
  (match e
    (,b (guard (boolean? b)) b)
    (,x (guard (symbol? x)) (v x))
    ((not ,e1) (not (ev e1 v)))
    ((and ,e1 ,e2) (and (ev e1 v) (ev e2 v)))
    ((or ,e1 ,e2) (or (ev e1 v) (ev e2 v)))
    ((=> ,e1 ,e2) (or (not (ev e1 v)) (ev e2 v)))
    ((<=> ,e1 ,e2) (eq? (ev e1 v) (ev e2 v)))))
(define (onAtoms f e)
  (match e
    (,b (guard (boolean? b)) b)
    (,x (guard (symbol? x)) (f x))
    ((not ,e1) `(not ,(onAtoms f e1)))
    ((,op ,e1 ,e2)
     `(,op ,(onAtoms f e1)
           ,(onAtoms f e2)))))
(define (atoms e)
  (match e
    (,b (guard (boolean? b)) '())
    (,x (guard (symbol? x)) (list x))
    ((not ,e1) (atoms e1))
    ((,op ,e1 ,e2) (U (atoms e1) (atoms e2)))))
(define (allv f v a*)
  (if (null? a*)
      (f v)
      (let ((a (car a*))
            (a* (cdr a*)))
        (define ((v^ b) x)
          (if (eq? x a) b (v x)))
        (and (allv f (v^ #f) a*)
             (allv f (v^ #t) a*)))))
(define (tautology? e)
  (allv (curry ev e)
        (lambda (x) #f)
        (atoms e)))
(define (unsatisfiable? e)
  (tautology? `(not ,e)))
(define (satisfiable? e)
  (not (unsatisfiable? e)))
(define (subst p x q)
  (onAtoms
   (lambda (y)
     (if (eq? x y) q y))
   p))
(define (psimplify exp)
  (define (Not exp)
    (match exp
      (,b (guard (boolean? b)) (not b))
      ((not ,e1) e1)
      (,else `(not ,exp))))
  (define (And e1 e2)
    (cond ((eq? e1 #f) #f)
          ((eq? e2 #f) #f)
          ((eq? e1 #t) e2)
          ((eq? e2 #t) e1)
          (else `(and ,e1 ,e2))))
  (define (Or e1 e2)
    (cond ((eq? e1 #t) #t)
          ((eq? e2 #t) #t)
          ((eq? e1 #f) e2)
          ((eq? e2 #f) e1)
          (else `(or ,e1 ,e2))))
  (define (Imp e1 e2)
    (cond ((eq? e1 #f) #t)
          ((eq? e2 #t) #t)
          ((eq? e1 #t) e2)
          ((eq? e2 #f) (Not e1))
          (else `(=> ,e1 ,e2))))
  (define (Iff e1 e2)
    (cond ((eq? e1 #t) e2)
          ((eq? e2 #t) e1)
          ((eq? e1 #f) (Not e2))
          ((eq? e2 #f) (Not e1))
          (else `(<=> ,e1 ,e2))))
  (define (simp exp)
    (match exp
      ((not ,e1) (Not (simp e1)))
      ((and ,e1 ,e2) (And (simp e1) (simp e2)))
      ((or ,e1 ,e2) (Or (simp e1) (simp e2)))
      ((=> ,e1 ,e2) (Imp (simp e1) (simp e2)))
      ((<=> ,e1 ,e2) (Iff (simp e1) (simp e2)))
      (,else exp)))
  (simp exp))
;<nnf> ::= <bool> | <nnf0>
;<nnf0> ::= <literal>
;        |  (and <nnf0> <nnf0>)
;        |  (or <nnf0> <nnf0>)
;<literal> ::= <var> | (not <var>)
(define (nnf exp)
  (define (Not exp)
    (match exp
      ((not ,e1) (nnf e1))
      ((and ,e1 ,e2)
       `(or ,(Not e1) ,(Not e2)))
      ((or ,e1 ,e2)
       `(and ,(Not e1) ,(Not e2)))
      ((=> ,e1 ,e2)
       `(and ,(nnf e1) ,(Not e2)))
      ((<=> ,e1 ,e2)
       `(or (and ,(nnf e1) ,(Not e2))
            (and ,(Not e1) ,(nnf e2))))
      (,else `(not ,exp))))
  (define (nnf exp)
    (match exp
      ((not ,e1) (Not e1))
      ((and ,e1 ,e2) `(and ,(nnf e1) ,(nnf e2)))
      ((or ,e1 ,e2) `(or ,(nnf e1) ,(nnf e2)))
      ((=> ,e1 ,e2) `(or ,(Not e1) ,(nnf e2)))
      ((<=> ,e1 ,e2)
       `(or (and ,(nnf e1) ,(nnf e2))
            (and ,(Not e1) ,(Not e2))))
      (,else exp)))
  (nnf (psimplify exp)))
(define (nnf? exp)
  (define (? exp)
    (match exp
      (,x (guard (symbol? x)) #t)
      ((not ,e1) (if (symbol? e1) #t #f))
      ((and ,e1 ,e2) (and (? e1) (? e2)))
      ((or ,e1 ,e2) (and (? e1) (? e2)))
      (,else #f)))
  (if (boolean? exp)
      #t
      (? exp)))
(define (make-conj x*)
  (cond ((null? x*) #t)
        ((null? (cdr x*)) (car x*))
        (else
         (let rec ((x (car x*))
                   (x* (cdr x*)))
           (if (null? x*)
               x
               `(and ,x ,(rec (car x*) (cdr x*))))))))
(define (make-disj x*)
  (cond ((null? x*) #f)
        ((null? (cdr x*)) (car x*))
        (else
         (let rec ((x (car x*))
                   (x* (cdr x*)))
           (if (null? x*)
               x
               `(or ,x ,(rec (car x*) (cdr x*))))))))
(define ((make-lits x*) v)
  (make-conj
   (map (lambda (x)
          (if (v x) x `(not ,x)))
        x*)))
(define (allsat f v a*)
  (if (null? a*)
      (if (f v) (list v) '())
      (let ((a (car a*))
            (a* (cdr a*)))
        (define ((v^ b) x)
          (if (eq? x a) b (v x)))
        (append (allsat f (v^ #f) a*)
                (allsat f (v^ #t) a*)))))
#;
(define (dnf exp)
  (let* ((a* (atoms exp))
         (v* (allsat (curry ev exp)
                     (lambda (x) #f)
                     a*)))
    (make-disj
     (map (make-lits a*) v*))))
;<dnf> ::= <bool> | <dnf0>
;<dnf0> ::= <conj> | (or <dnf0> <dnf0>)
;<conj> ::= <literal> | (and <conj> <conj>)
;<literal> ::= <var> | (not <var>)
(define (allpairs f x* y*)
  (append-map
   (lambda (y)
     (map (lambda (x) (f x y)) x*))
   y*))
(define (negative? literal)
  (and (pair? literal)
       (eq? (car literal) 'not)))
(define (positive? literal)
  (not (negative? literal)))
(define (negate literal)
  (match literal
    ((not ,atom) atom)
    (,else `(not ,literal))))
(define (trivial? lits)
  (let-values (((p n) (partition positive? lits)))
    (I? p (map negate n))))
(define (subsume exp)
  (let rec ((rest (sort (filter (compose not trivial?) exp)
                        > #:key length)))
    (cond ((null? rest) '())
          ((memf (lambda (d)
                   (subset? d (car rest)))
                 (cdr rest))
           (rec (cdr rest)))
          (else (cons (car rest)
                      (rec (cdr rest)))))))
(define (purednf0 exp)
  (define (distrib s1 s2)
    (setlize (allpairs U s1 s2)))
  (define (dnf exp)
    (match exp
      ((and ,e1 ,e2)
       (distrib (dnf e1) (dnf e2)))
      ((or ,e1 ,e2)
       (U (dnf e1) (dnf e2)))
      (,else `((,exp)))))
  (cond ((eq? exp #f) '())
        ((eq? exp #t) '(()))
        (else (dnf exp))))
(define purednf
  (compose purednf0 nnf))
(define (simpdnf exp)
  (subsume (purednf exp)))
(define (make-dnf lst)
  (make-disj (map make-conj lst)))
(define (dnf exp)
  (make-dnf (simpdnf exp)))
(define (purecnf exp)
  (map (curry map negate)
       (purednf `(not ,exp))))
(define (simpcnf exp)
  (subsume (purecnf exp)))
(define (make-cnf lst)
  (make-conj (map make-disj lst)))
(define (cnf exp)
  (make-cnf (simpcnf exp)))
(define (nenf exp)
  (define (Not exp)
    (match exp
      ((not ,e1) (nenf e1))
      ((and ,e1 ,e2)
       `(or ,(Not e1) ,(Not e2)))
      ((or ,e1 ,e2)
       `(and ,(Not e1) ,(Not e2)))
      ((=> ,e1 ,e2)
       `(and ,(nenf e1) ,(Not e2)))
      ((<=> ,e1 ,e2)
       `(<=> ,(nenf e1) ,(Not e2)))
      (,else `(not ,exp))))
  (define (nenf exp)
    (match exp
      ((not ,e1) (Not e1))
      ((and ,e1 ,e2) `(and ,(nenf e1) ,(nenf e2)))
      ((or ,e1 ,e2) `(or ,(nenf e1) ,(nenf e2)))
      ((=> ,e1 ,e2) `(or ,(Not e1) ,(nenf e2)))
      ((<=> ,e1 ,e2)
       `(<=> ,(nenf e1) ,(nenf e2)))
      (,else exp)))
  (nenf (psimplify exp)))
(define (fresh-var)
  (gensym 'p_))
#;
(define (tseitin exp)
  (define (tseitin exp d*)
    (match exp
      ((,op ,e1 ,e2)
       (let*-values (((l1 d*) (tseitin e1 d*))
                     ((l2 d*) (tseitin e2 d*)))
         (let ((x (fresh-var))
               (e `(,op ,l1 ,l2)))
           (values x (cons `(<=> ,x ,e) d*)))))
      (,else (values exp d*))))
  (tseitin (nenf exp) '()))
#;
(define (tseitin exp)
  (define (lookup e d*)
    (match d*
      (((<=> ,x ,p) . ,d*)
       (if (equal? e p)
           x
           (lookup e d*)))
      (,else #f)))
  (define (tseitin exp d*)
    (match exp
      ((,op ,e1 ,e2)
       (let*-values (((l1 d*) (tseitin e1 d*))
                     ((l2 d*) (tseitin e2 d*)))
         (define e `(,op ,l1 ,l2))
         (define x (lookup e d*))
         (if x
             (values x d*)
             (let ((x (fresh-var)))
               (values x (cons `(<=> ,x ,e) d*))))))
      (,else (values exp d*))))
  (tseitin (nenf exp) '()))
;<cnf> ::= <bool> | <cnf0>
;<cnf0> ::= <disj> | (and <cnf0> <cnf0>)
;<disj> ::= <literal> | (or <disj> <disj>)
(define (tseitin exp)
  (define (lookup e d*)
    (match d*
      (((<=> ,x ,p) . ,d*)
       (if (equal? e p)
           x
           (lookup e d*)))
      (,else #f)))
  (define (Exp step op e1 e2 d*)
    (let*-values (((e1 d*) (step e1 d*))
                  ((e2 d*) (step e2 d*)))
      (values `(,op ,e1 ,e2) d*)))
  (define (CNF exp d*)
    (match exp
      ((and ,e1 ,e2) (Exp CNF 'and e1 e2 d*))
      (,else (Conjunct exp d*))))
  (define (Conjunct exp d*)
    (match exp
      ((or ,e1 ,e2) (Exp Conjunct 'or e1 e2 d*))
      (,else (Literal exp d*))))
  (define (Literal exp d*)
    (match exp
      ((,op ,e1 ,e2)
       (let-values (((e d*) (Exp Literal op e1 e2 d*)))
         (define x (lookup e d*))
         (if x
             (values x d*)
             (let ((x (fresh-var)))
               (values x (cons `(<=> ,x ,e) d*))))))
      (,else (values exp d*))))
  (CNF (nenf exp) '()))
(define (defcnf exp)
  (let-values (((p d*) (tseitin exp)))
    (append-map simpcnf (cons p d*))))
(define e0
  '(and (or p (and q (not r))) s))
(define e1
  '(or (and (or p q) (or p q))
       (and (or p q) (or p q))))
(define (one-literal-rule clauses)
  (define lit
    (let ((m (memf (lambda (clause)
                     (if (null? clause)
                         #f
                         (null? (cdr clause))))
                   clauses)))
      (and m (caar m))))
  (and lit
       (map (curry remove (negate lit))
            (filter (lambda (clause)
                      (not (member lit clause)))
                    clauses))))
(define (image f x*)
  (setlize (map f x*)))
(define (affirmative-negative-rule clauses)
  (let-values (((neg^ pos) (partition negative? (apply U* clauses))))
    (define neg (image negate neg^))
    (define pos_only (D pos neg))
    (define neg_only (D neg pos))
    (define pure
      (U pos_only (map negate neg_only)))
    (if (null? pure)
        #f
        (filter (lambda (clause)
                  (not (I? pure clause)))
                clauses))))
;(affirmative-negative-rule '((p (not r)) (p r) (q r) ((not q) r)))
(define (resolve-on p clauses)
  (define -p (negate p))
  (define-values (pos notpos)
    (partition (curry member p) clauses))
  (define-values (neg other)
    (partition (curry member -p) notpos))
  (define C*
    (map (curry filter (lambda (l)
                         (not (equal? l p))))
         pos))
  (define D*
    (map (curry filter (lambda (l)
                         (not (equal? l -p))))
         neg))
  (define res0 (allpairs U C* D*))
  (U other (filter (compose not trivial?) res0)))
;(resolve-on 'p '((p (not q)) ((not p) q) (q)))
(define ((resolution-blowup clauses) literal)
  (define m
    (length
     (filter (curry member literal) clauses)))
  (define n
    (length
     (filter (curry member (negate literal)) clauses)))
  (- (* m n) m n))
(define (minimize f x*)
  (let iter ((x (car x*))
             (m (f (car x*)))
             (x* (cdr x*)))
    (if (null? x*)
        x
        (let ((n (f (car x*))))
          (if (< n m)
              (iter (car x*) n (cdr x*))
              (iter x m (cdr x*)))))))
(define (maximize f x*)
  (let iter ((x (car x*))
             (m (f (car x*)))
             (x* (cdr x*)))
    (if (null? x*)
        x
        (let ((n (f (car x*))))
          (if (> n m)
              (iter (car x*) n (cdr x*))
              (iter x m (cdr x*)))))))
(define (resolution-rule clauses)
  (define p*
    (filter positive? (apply U* clauses)))
  (define p
    (minimize (resolution-blowup clauses) p*))
  (resolve-on p clauses))
(define (dp clauses)
  (cond ((null? clauses) #t)
        ((member '() clauses) #f)
        (else
         (let ((new (one-literal-rule clauses)))
           (if new (dp new)
               (let ((new (affirmative-negative-rule clauses)))
                 (if new (dp new)
                     (dp (resolution-rule clauses)))))))))
(define (dpsat? exp)
  (dp (defcnf exp)))
(define (dptaut? exp)
  (not (dpsat? `(not ,exp))))
(define ((posneg-count clauses) literal)
  (define m
    (length
     (filter (curry member literal) clauses)))
  (define n
    (length
     (filter (curry member (negate literal)) clauses)))
  (+ m n))
(define (dpll clauses)
  (cond ((null? clauses) #t)
        ((member '() clauses) #f)
        (else
         (let ((new (one-literal-rule clauses)))
           (if new (dpll new)
               (let ((new (affirmative-negative-rule clauses)))
                 (if new (dpll new)
                     (splitting-rule clauses))))))))
(define (splitting-rule clauses)
  (define p*
    (filter positive? (apply U* clauses)))
  (define p
    (maximize (posneg-count clauses) p*))
  (or (dpll (cons (list p) clauses))
      (dpll (cons (list (negate p)) clauses))))
(define (dpllsat? exp)
  (dpll (defcnf exp)))
(define (dplltaut? exp)
  (not (dpllsat? `(not ,exp))))
(define e2
  '(and (<=> (or p q) (=> (not p) q))
        (<=> (or p q) (=> (not q) p))))
(define ((allsets n) s)
  (define (a n s l)
    (cond ((= n 0) '(()))
          ((< l n) '())
          ((= l n) (list s))
          (else
           (append (map (curry cons (car s))
                        (a (- n 1) (cdr s) (- l 1)))
                   (a n (cdr s) (- l 1))))))
  (a n s (length s)))
(define (ramsey s t n)
  (define v* (range n))
  (define (sub x)
    (map (allsets 2)
         ((allsets x) v*)))
  (define yes* (sub s))
  (define no* (sub t))
  (define (e p)
    (string->symbol
     (apply format "p_~s_~s" p)))
  (make-disj
   (append (map (lambda (p*)
                  (make-conj (map e p*)))
                yes*)
           (map (lambda (p*)
                  (make-conj (map (lambda (p)
                                    `(not ,(e p)))
                                  p*)))
                no*))))
;(dplltaut? (ramsey 3 3 6))

;<term> ::= <var> | (<func> <term>*)
;<predicate> ::= (<pred> <term>*)
;<exp> ::= <bool>
;       |  <predicate>
;       |  (not <exp>)
;       |  (and <exp> <exp>)
;       |  (or <exp> <exp>)
;       |  (=> <exp> <exp>)
;       |  (<=> <exp> <exp>)
;       |  (forall <var> <exp>)
;       |  (exists <var> <exp>)
(struct interp (domain func pred))
(define ((termval m v) term)
  (match term
    (,x (guard (symbol? x)) (v x))
    ((,func . ,term*)
     (apply (funcval m func)
            (map (termval m v) term*)))))
(define (funcval m f)
  ((interp-func m) f))
(define (predval m p)
  ((interp-pred m) p))
(define (extend v x a)
  (lambda (y)
    (if (eq? y x)
        a
        (v y))))
(define (holds? m v exp)
  (match exp
    (,b (guard (boolean? b)) b)
    ((not ,e) (not (holds? m v e)))
    ((and ,e1 ,e2) (and (holds? m v e1)
                        (holds? m v e2)))
    ((or ,e1 ,e2) (or (holds? m v e1)
                      (holds? m v e2)))
    ((=> ,e1 ,e2) (or (not (holds? m v e1))
                      (holds? m v e2)))
    ((<=> ,e1 ,e2) (eq? (holds? m v e1)
                        (holds? m v e2)))
    ((forall ,x ,e)
     (forall? (lambda (a)
                (holds? m (extend v x a) e))
              (interp-domain m)))
    ((exists ,x ,e)
     (exists? (lambda (a)
                (holds? m (extend v x a) e))
              (interp-domain m)))
    ((,pred . ,term*)
     (apply (predval m pred)
            (map (termval m v) term*)))))
(define boole
  (interp '(#f #t)
          (lambda (f)
            (case f
              ((zero) (lambda () #f))
              ((one) (lambda () #t))
              ;exclusive or
              ((+) (lambda (a b)
                     (not (eq? a b))))
              ((*) (lambda (a b)
                     (and a b)))
              (else (error 'boole "unknown func symbol ~s" f))))
          (lambda (p)
            (case p
              ((=) (lambda (a b)
                     (eq? a b)))
              (else (error 'boole "unknown pred symbol ~s" p))))))
(define (mod-interp n)
  (interp (range n)
          (lambda (f)
            (case f
              ((zero) (lambda () 0))
              ((one) (lambda () (modulo 1 n)))
              ((+) (lambda (a b)
                     (modulo (+ a b) n)))
              ((*) (lambda (a b)
                     (modulo (* a b) n)))
              (else (error 'mod-interp "unknown func symbol ~s" f))))
          (lambda (p)
            (case p
              ((=) (lambda (a b) (= a b)))
              (else (error 'mod-interp "unknown pred symbol ~s" p))))))
(define undefined
  (lambda (x)
    (error 'undefined "unknown variable ~s" x)))
(define modulo_inverse_existence
  '(forall x (=> (not (= x (zero)))
                 (exists y (= (* x y) (one))))))
#;
(filter (lambda (n)
          (holds? (mod-interp n) undefined
                  modulo_inverse_existence))
        (range 1 100))