#lang racket
(require "match.rkt")
;set operations
(define (U s1 s2)
  (cond ((null? s1) s2)
        ((member (car s1) s2) (U (cdr s1) s2))
        (else (cons (car s1) (U (cdr s1) s2)))))
(define (set-cons x s)
  (if (member x s)
      s
      (cons x s)))
(define (setlize x*)
  (if (null? x*)
      '()
      (set-cons (car x*)
                (setlize (cdr x*)))))
(define (I? s1 s2)
  (cond ((null? s1) #f)
        ((member (car s1) s2) #t)
        (else (I? (cdr s1) s2))))
(define (subset? s1 s2)
  (cond ((null? s1) #t)
        ((member (car s1) s2)
         (subset? (cdr s1) s2))
        (else #f)))
;<exp> ::= <bool>
;       |  <var>
;       |  (not <exp>)
;       |  (and <exp> <exp>)
;       |  (or <exp> <exp>)
;       |  (=> <exp> <exp>)
;       |  (<=> <exp> <exp>)
(define peirce
  '(=> (=> (=> p q) p) p))
(define p<=>q<=>r
  '(<=> p (<=> q r)))
(define (ev e v)
  (match e
    (,b (guard (boolean? b)) b)
    (,x (guard (symbol? x)) (v x))
    ((not ,e1) (not (ev e1 v)))
    ((and ,e1 ,e2) (and (ev e1 v) (ev e2 v)))
    ((or ,e1 ,e2) (or (ev e1 v) (ev e2 v)))
    ((=> ,e1 ,e2) (or (not (ev e1 v)) (ev e2 v)))
    ((<=> ,e1 ,e2) (eq? (ev e1 v) (ev e2 v)))))
(define (onAtoms f e)
  (match e
    (,b (guard (boolean? b)) b)
    (,x (guard (symbol? x)) (f x))
    ((not ,e1) `(not ,(onAtoms f e1)))
    ((,op ,e1 ,e2)
     `(,op ,(onAtoms f e1)
           ,(onAtoms f e2)))))
(define (atoms e)
  (match e
    (,b (guard (boolean? b)) '())
    (,x (guard (symbol? x)) (list x))
    ((not ,e1) (atoms e1))
    ((,op ,e1 ,e2) (U (atoms e1) (atoms e2)))))
(define (allv f v a*)
  (if (null? a*)
      (f v)
      (let ((a (car a*))
            (a* (cdr a*)))
        (define ((v^ b) x)
          (if (eq? x a) b (v x)))
        (and (allv f (v^ #f) a*)
             (allv f (v^ #t) a*)))))
(define (tautology? e)
  (allv (curry ev e)
        (lambda (x) #f)
        (atoms e)))
(define (unsatisfiable? e)
  (tautology? `(not ,e)))
(define (satisfiable? e)
  (not (unsatisfiable? e)))
(define (subst p x q)
  (onAtoms
   (lambda (y)
     (if (eq? x y) q y))
   p))
(define (psimplify exp)
  (define (Not exp)
    (match exp
      (,b (guard (boolean? b)) (not b))
      ((not ,e1) e1)
      (,else `(not ,exp))))
  (define (And e1 e2)
    (cond ((eq? e1 #f) #f)
          ((eq? e2 #f) #f)
          ((eq? e1 #t) e2)
          ((eq? e2 #t) e1)
          (else `(and ,e1 ,e2))))
  (define (Or e1 e2)
    (cond ((eq? e1 #t) #t)
          ((eq? e2 #t) #t)
          ((eq? e1 #f) e2)
          ((eq? e2 #f) e1)
          (else `(or ,e1 ,e2))))
  (define (Imp e1 e2)
    (cond ((eq? e1 #f) #t)
          ((eq? e2 #t) #t)
          ((eq? e1 #t) e2)
          ((eq? e2 #f) (Not e1))
          (else `(=> ,e1 ,e2))))
  (define (Iff e1 e2)
    (cond ((eq? e1 #t) e2)
          ((eq? e2 #t) e1)
          ((eq? e1 #f) (Not e2))
          ((eq? e2 #f) (Not e1))
          (else `(<=> ,e1 ,e2))))
  (define (simp exp)
    (match exp
      ((not ,e1) (Not (simp e1)))
      ((and ,e1 ,e2) (And (simp e1) (simp e2)))
      ((or ,e1 ,e2) (Or (simp e1) (simp e2)))
      ((=> ,e1 ,e2) (Imp (simp e1) (simp e2)))
      ((<=> ,e1 ,e2) (Iff (simp e1) (simp e2)))
      (,else exp)))
  (simp exp))
;<nnf> ::= <bool> | <nnf0>
;<nnf0> ::= <literal>
;        |  (and <nnf0> <nnf0>)
;        |  (or <nnf0> <nnf0>)
;<literal> ::= <var> | (not <var>)
(define (nnf exp)
  (define (Not exp)
    (match exp
      ((not ,e1) (nnf e1))
      ((and ,e1 ,e2)
       `(or ,(Not e1) ,(Not e2)))
      ((or ,e1 ,e2)
       `(and ,(Not e1) ,(Not e2)))
      ((=> ,e1 ,e2)
       `(and ,(nnf e1) ,(Not e2)))
      ((<=> ,e1 ,e2)
       `(or (and ,(nnf e1) ,(Not e2))
            (and ,(Not e1) ,(nnf e2))))
      (,else `(not ,exp))))
  (define (nnf exp)
    (match exp
      ((not ,e1) (Not e1))
      ((and ,e1 ,e2) `(and ,(nnf e1) ,(nnf e2)))
      ((or ,e1 ,e2) `(or ,(nnf e1) ,(nnf e2)))
      ((=> ,e1 ,e2) `(or ,(Not e1) ,(nnf e2)))
      ((<=> ,e1 ,e2)
       `(or (and ,(nnf e1) ,(nnf e2))
            (and ,(Not e1) ,(Not e2))))
      (,else exp)))
  (nnf (psimplify exp)))
(define (nnf? exp)
  (define (? exp)
    (match exp
      (,x (guard (symbol? x)) #t)
      ((not ,e1) (if (symbol? e1) #t #f))
      ((and ,e1 ,e2) (and (? e1) (? e2)))
      ((or ,e1 ,e2) (and (? e1) (? e2)))
      (,else #f)))
  (if (boolean? exp)
      #t
      (? exp)))
(define (make-conj x*)
  (cond ((null? x*) #t)
        ((null? (cdr x*)) (car x*))
        (else
         (let rec ((x (car x*))
                   (x* (cdr x*)))
           (if (null? x*)
               x
               `(and ,x ,(rec (car x*) (cdr x*))))))))
(define (make-disj x*)
  (cond ((null? x*) #f)
        ((null? (cdr x*)) (car x*))
        (else
         (let rec ((x (car x*))
                   (x* (cdr x*)))
           (if (null? x*)
               x
               `(or ,x ,(rec (car x*) (cdr x*))))))))
(define ((make-lits x*) v)
  (make-conj
   (map (lambda (x)
          (if (v x) x `(not ,x)))
        x*)))
(define (allsat f v a*)
  (if (null? a*)
      (if (f v) (list v) '())
      (let ((a (car a*))
            (a* (cdr a*)))
        (define ((v^ b) x)
          (if (eq? x a) b (v x)))
        (append (allsat f (v^ #f) a*)
                (allsat f (v^ #t) a*)))))
#;
(define (dnf exp)
  (let* ((a* (atoms exp))
         (v* (allsat (curry ev exp)
                     (lambda (x) #f)
                     a*)))
    (make-disj
     (map (make-lits a*) v*))))
;<dnf> ::= <bool> | <dnf0>
;<dnf0> ::= <conj> | (or <dnf0> <dnf0>)
;<conj> ::= <literal> | (and <conj> <conj>)
;<literal> ::= <var> | (not <var>)
(define (allpairs f x* y*)
  (append-map
   (lambda (y)
     (map (lambda (x) (f x y)) x*))
   y*))
(define (negative? literal)
  (and (pair? literal)
       (eq? (car literal) 'not)))
(define (positive? literal)
  (not (negative? literal)))
(define (negate literal)
  (match literal
    ((not ,atom) atom)
    (,else `(not ,literal))))
(define (trivial? lits)
  (let-values (((p n) (partition positive? lits)))
    (I? p (map negate n))))
(define (subsume exp)
  (let rec ((rest (sort (filter (compose not trivial?) exp)
                        > #:key length)))
    (cond ((null? rest) '())
          ((memf (lambda (d)
                   (subset? d (car rest)))
                 (cdr rest))
           (rec (cdr rest)))
          (else (cons (car rest)
                      (rec (cdr rest)))))))
(define (purednf0 exp)
  (define (distrib s1 s2)
    (setlize (allpairs U s1 s2)))
  (define (dnf exp)
    (match exp
      ((and ,e1 ,e2)
       (distrib (dnf e1) (dnf e2)))
      ((or ,e1 ,e2)
       (U (dnf e1) (dnf e2)))
      (,else `((,exp)))))
  (cond ((eq? exp #f) '())
        ((eq? exp #t) '(()))
        (else (dnf exp))))
(define purednf
  (compose purednf0 nnf))
(define (simpdnf exp)
  (subsume (purednf exp)))
(define (dnf exp)
  (make-disj
   (map make-conj (simpdnf exp))))
(define (purecnf exp)
  (map (curry map negate)
       (purednf `(not ,exp))))
(define (simpcnf exp)
  (subsume (purecnf exp)))
(define (cnf exp)
  (make-conj
   (map make-disj (simpcnf exp))))
(define (nenf exp)
  (define (Not exp)
    (match exp
      ((not ,e1) (nenf e1))
      ((and ,e1 ,e2)
       `(or ,(Not e1) ,(Not e2)))
      ((or ,e1 ,e2)
       `(and ,(Not e1) ,(Not e2)))
      ((=> ,e1 ,e2)
       `(and ,(nenf e1) ,(Not e2)))
      ((<=> ,e1 ,e2)
       `(<=> ,(nenf e1) ,(Not e2)))
      (,else `(not ,exp))))
  (define (nenf exp)
    (match exp
      ((not ,e1) (Not e1))
      ((and ,e1 ,e2) `(and ,(nenf e1) ,(nenf e2)))
      ((or ,e1 ,e2) `(or ,(nenf e1) ,(nenf e2)))
      ((=> ,e1 ,e2) `(or ,(Not e1) ,(nenf e2)))
      ((<=> ,e1 ,e2)
       `(<=> ,(nenf e1) ,(nenf e2)))
      (,else exp)))
  (nenf (psimplify exp)))
(define (fresh-var)
  (gensym 'p_))
(define (tseitin exp)
  (define (tseitin exp d*)
    (match exp
      ((,op ,e1 ,e2)
       (let*-values (((p1 d*) (tseitin e1 d*))
                     ((p2 d*) (tseitin e2 d*)))
         (let ((x (fresh-var))
               (e `(,op ,p1 ,p2)))
           (values x (cons `(<=> ,x ,e) d*)))))
      (,else (values exp d*))))
  (tseitin (nenf exp) '()))
(define (defcnf exp)
  (let-values (((p d*) (tseitin exp)))
    (make-conj
     (map make-disj
          (append-map simpcnf (cons p d*))))))
