#lang racket
;<contract> ::= (Zero)
;            |  (One <currency>)
;            |  (Give <contract>)
;            |  (And <contract> <contract>)
;            |  (Or <contract> <contract>)
;            |  (Cond <observable> <contract> <contract>)
;            |  (Scale <observable> <contract>)
;            |  (When <observable> <contract>)
;            |  (Anytime <observable> <contract>)
;            |  (Until <observable> <contract>)
;contract primitives
(struct Zero () #:transparent)
(struct One (currency) #:transparent)
(struct Give (contract) #:transparent)
(struct And (c1 c2) #:transparent)
(struct Or (c1 c2) #:transparent)
(struct Cond (observable c1 c2) #:transparent)
(struct Scale (observable contract) #:transparent)
(struct When (observable contract) #:transparent)
(struct Anytime (observable contract) #:transparent)
(struct Until (observable contract) #:transparent)
;observable primitives
(struct Konst (v) #:transparent)
(struct Time () #:transparent)
(struct Proj (id) #:transparent)
(struct Lift (f o) #:transparent)
(struct Lift2 (f o1 o2) #:transparent)
(define ((lift f) x)
  (lambda (time world)
    (f (x time world))))
(define ((lift2 f) x y)
  (lambda (time world)
    (f (x time world)
       (y time world))))
(define (Observe x)
  (match x
    ((Konst v) (lambda (time world) v))
    ((Time) (lambda (time world) time))
    ((Proj id) (lambda (time world)
                 (world 'lookup id time)))
    ((Lift f o) ((lift f) (Observe o)))
    ((Lift2 f o1 o2)
     ((lift2 f) (Observe o1) (Observe o2)))))
(define (At time)
  (Lift2 = (Konst time) (Time)))
(define (ScaleK n c)
  (Scale (Konst n) c))
(define (zcb t n k)
  (When (At t) (ScaleK n (One k))))
(define (If ob p1 p2)
  (lambda (time world)
    (if (ob time world)
        (p1 time world)
        (p2 time world))))
(define (Eval contract k)
  (match contract
    ((Zero) (lambda (time world) 0))
    ((Give c) ((lift -) (Eval c k)))
    ((And c1 c2) ((lift2 +) (Eval c1 k) (Eval c2 k)))
    ((Or c1 c2) ((lift2 max) (Eval c1 k) (Eval c2 k)))
    ((Cond o c1 c2)
     (If (Observe o)
         (Eval c1 k)
         (Eval c2 k)))
    ((Scale o c) ((lift2 *) (Observe o) (Eval c k)))
    
    ))
