#lang racket
(provide (all-defined-out))
(define (A #:attr* [attr* '()] . sxml*)
  `(a ,attr* . ,sxml*))
(define (Abbr #:attr* [attr* '()] . sxml*)
  `(abbr ,attr* . ,sxml*))
(define (Address #:attr* [attr* '()] . sxml*)
  `(address ,attr* . ,sxml*))
(define (Area #:attr* [attr* '()] . sxml*)
  `(area ,attr* . ,sxml*))
(define (Article #:attr* [attr* '()] . sxml*)
  `(article ,attr* . ,sxml*))
(define (Aside #:attr* [attr* '()] . sxml*)
  `(aside ,attr* . ,sxml*))
(define (Audio #:attr* [attr* '()] . sxml*)
  `(audio ,attr* . ,sxml*))
(define (B #:attr* [attr* '()] . sxml*)
  `(b ,attr* . ,sxml*))
(define (Base #:attr* [attr* '()] . sxml*)
  `(base ,attr* . ,sxml*))
(define (Bdi #:attr* [attr* '()] . sxml*)
  `(bdi ,attr* . ,sxml*))
(define (Bdo #:attr* [attr* '()] . sxml*)
  `(bdo ,attr* . ,sxml*))
(define (Blockquote #:attr* [attr* '()] . sxml*)
  `(blockquote ,attr* . ,sxml*))
(define (Body #:attr* [attr* '()] . sxml*)
  `(body ,attr* . ,sxml*))
(define (Br #:attr* [attr* '()] . sxml*)
  `(br ,attr* . ,sxml*))
(define (Button #:attr* [attr* '()] . sxml*)
  `(button ,attr* . ,sxml*))
(define (Canvas #:attr* [attr* '()] . sxml*)
  `(canvas ,attr* . ,sxml*))
(define (Caption #:attr* [attr* '()] . sxml*)
  `(caption ,attr* . ,sxml*))
(define (Cite #:attr* [attr* '()] . sxml*)
  `(cite ,attr* . ,sxml*))
(define (Code #:attr* [attr* '()] . sxml*)
  `(code ,attr* . ,sxml*))
(define (Col #:attr* [attr* '()] . sxml*)
  `(col ,attr* . ,sxml*))
(define (Colgroup #:attr* [attr* '()] . sxml*)
  `(colgroup ,attr* . ,sxml*))
(define (Data #:attr* [attr* '()] . sxml*)
  `(data ,attr* . ,sxml*))
(define (Datalist #:attr* [attr* '()] . sxml*)
  `(datalist ,attr* . ,sxml*))
(define (Dd #:attr* [attr* '()] . sxml*)
  `(dd ,attr* . ,sxml*))
(define (Del #:attr* [attr* '()] . sxml*)
  `(del ,attr* . ,sxml*))
(define (Details #:attr* [attr* '()] . sxml*)
  `(details ,attr* . ,sxml*))
(define (Dfn #:attr* [attr* '()] . sxml*)
  `(dfn ,attr* . ,sxml*))
(define (Dialog #:attr* [attr* '()] . sxml*)
  `(dialog ,attr* . ,sxml*))
(define (Div #:attr* [attr* '()] . sxml*)
  `(div ,attr* . ,sxml*))
(define (Dl #:attr* [attr* '()] . sxml*)
  `(dl ,attr* . ,sxml*))
(define (Dt #:attr* [attr* '()] . sxml*)
  `(dt ,attr* . ,sxml*))
(define (Em #:attr* [attr* '()] . sxml*)
  `(em ,attr* . ,sxml*))
(define (Embed #:attr* [attr* '()] . sxml*)
  `(embed ,attr* . ,sxml*))
(define (Fieldset #:attr* [attr* '()] . sxml*)
  `(fieldset ,attr* . ,sxml*))
(define (Figcaption #:attr* [attr* '()] . sxml*)
  `(figcaption ,attr* . ,sxml*))
(define (Figure #:attr* [attr* '()] . sxml*)
  `(figure ,attr* . ,sxml*))
(define (Footer #:attr* [attr* '()] . sxml*)
  `(footer ,attr* . ,sxml*))
(define (Form #:attr* [attr* '()] . sxml*)
  `(form ,attr* . ,sxml*))
(define (H1 #:attr* [attr* '()] . sxml*)
  `(h1 ,attr* . ,sxml*))
(define (Head #:attr* [attr* '()] . sxml*)
  `(head ,attr* . ,sxml*))
(define (Header #:attr* [attr* '()] . sxml*)
  `(header ,attr* . ,sxml*))
(define (Hgroup #:attr* [attr* '()] . sxml*)
  `(hgroup ,attr* . ,sxml*))
(define (Hr #:attr* [attr* '()] . sxml*)
  `(hr ,attr* . ,sxml*))
(define (Html #:attr* [attr* '()] . sxml*)
  `(html ,attr* . ,sxml*))
(define (I #:attr* [attr* '()] . sxml*)
  `(i ,attr* . ,sxml*))
(define (Iframe #:attr* [attr* '()] . sxml*)
  `(iframe ,attr* . ,sxml*))
(define (Img #:attr* [attr* '()] . sxml*)
  `(img ,attr* . ,sxml*))
(define (Input #:attr* [attr* '()] . sxml*)
  `(input ,attr* . ,sxml*))
(define (Ins #:attr* [attr* '()] . sxml*)
  `(ins ,attr* . ,sxml*))
(define (Kbd #:attr* [attr* '()] . sxml*)
  `(kbd ,attr* . ,sxml*))
(define (Label #:attr* [attr* '()] . sxml*)
  `(label ,attr* . ,sxml*))
(define (Legend #:attr* [attr* '()] . sxml*)
  `(legend ,attr* . ,sxml*))
(define (Li #:attr* [attr* '()] . sxml*)
  `(li ,attr* . ,sxml*))
(define (Link #:attr* [attr* '()] . sxml*)
  `(link ,attr* . ,sxml*))
(define (Main #:attr* [attr* '()] . sxml*)
  `(main ,attr* . ,sxml*))
(define (Map #:attr* [attr* '()] . sxml*)
  `(map ,attr* . ,sxml*))
(define (Mark #:attr* [attr* '()] . sxml*)
  `(mark ,attr* . ,sxml*))
(define (Menu #:attr* [attr* '()] . sxml*)
  `(menu ,attr* . ,sxml*))
(define (Meta #:attr* [attr* '()] . sxml*)
  `(meta ,attr* . ,sxml*))
(define (Meter #:attr* [attr* '()] . sxml*)
  `(meter ,attr* . ,sxml*))
(define (Nav #:attr* [attr* '()] . sxml*)
  `(nav ,attr* . ,sxml*))
(define (Noscript #:attr* [attr* '()] . sxml*)
  `(noscript ,attr* . ,sxml*))
(define (Object #:attr* [attr* '()] . sxml*)
  `(object ,attr* . ,sxml*))
(define (Ol #:attr* [attr* '()] . sxml*)
  `(ol ,attr* . ,sxml*))
(define (Optgroup #:attr* [attr* '()] . sxml*)
  `(optgroup ,attr* . ,sxml*))
(define (Option #:attr* [attr* '()] . sxml*)
  `(option ,attr* . ,sxml*))
(define (Output #:attr* [attr* '()] . sxml*)
  `(output ,attr* . ,sxml*))
(define (P #:attr* [attr* '()] . sxml*)
  `(p ,attr* . ,sxml*))
(define (Picture #:attr* [attr* '()] . sxml*)
  `(picture ,attr* . ,sxml*))
(define (Pre #:attr* [attr* '()] . sxml*)
  `(pre ,attr* . ,sxml*))
(define (Progress #:attr* [attr* '()] . sxml*)
  `(progress ,attr* . ,sxml*))
(define (Q #:attr* [attr* '()] . sxml*)
  `(q ,attr* . ,sxml*))
(define (Rp #:attr* [attr* '()] . sxml*)
  `(rp ,attr* . ,sxml*))
(define (Rt #:attr* [attr* '()] . sxml*)
  `(rt ,attr* . ,sxml*))
(define (Ruby #:attr* [attr* '()] . sxml*)
  `(ruby ,attr* . ,sxml*))
(define (S #:attr* [attr* '()] . sxml*)
  `(s ,attr* . ,sxml*))
(define (Samp #:attr* [attr* '()] . sxml*)
  `(samp ,attr* . ,sxml*))
(define (Script #:attr* [attr* '()] . sxml*)
  `(script ,attr* . ,sxml*))
(define (Search #:attr* [attr* '()] . sxml*)
  `(search ,attr* . ,sxml*))
(define (Section #:attr* [attr* '()] . sxml*)
  `(section ,attr* . ,sxml*))
(define (Select #:attr* [attr* '()] . sxml*)
  `(select ,attr* . ,sxml*))
(define (Slot #:attr* [attr* '()] . sxml*)
  `(slot ,attr* . ,sxml*))
(define (Small #:attr* [attr* '()] . sxml*)
  `(small ,attr* . ,sxml*))
(define (Source #:attr* [attr* '()] . sxml*)
  `(source ,attr* . ,sxml*))
(define (Span #:attr* [attr* '()] . sxml*)
  `(span ,attr* . ,sxml*))
(define (Strong #:attr* [attr* '()] . sxml*)
  `(strong ,attr* . ,sxml*))
(define (Style #:attr* [attr* '()] . sxml*)
  `(style ,attr* . ,sxml*))
(define (Sub #:attr* [attr* '()] . sxml*)
  `(sub ,attr* . ,sxml*))
(define (Summary #:attr* [attr* '()] . sxml*)
  `(summary ,attr* . ,sxml*))
(define (Sup #:attr* [attr* '()] . sxml*)
  `(sup ,attr* . ,sxml*))
(define (Table #:attr* [attr* '()] . sxml*)
  `(table ,attr* . ,sxml*))
(define (Tbody #:attr* [attr* '()] . sxml*)
  `(tbody ,attr* . ,sxml*))
(define (Td #:attr* [attr* '()] . sxml*)
  `(td ,attr* . ,sxml*))
(define (Template #:attr* [attr* '()] . sxml*)
  `(template ,attr* . ,sxml*))
(define (Textarea #:attr* [attr* '()] . sxml*)
  `(textarea ,attr* . ,sxml*))
(define (Tfoot #:attr* [attr* '()] . sxml*)
  `(tfoot ,attr* . ,sxml*))
(define (Th #:attr* [attr* '()] . sxml*)
  `(th ,attr* . ,sxml*))
(define (Thead #:attr* [attr* '()] . sxml*)
  `(thead ,attr* . ,sxml*))
(define (Time #:attr* [attr* '()] . sxml*)
  `(time ,attr* . ,sxml*))
(define (Title #:attr* [attr* '()] . sxml*)
  `(title ,attr* . ,sxml*))
(define (Tr #:attr* [attr* '()] . sxml*)
  `(tr ,attr* . ,sxml*))
(define (Track #:attr* [attr* '()] . sxml*)
  `(track ,attr* . ,sxml*))
(define (U #:attr* [attr* '()] . sxml*)
  `(u ,attr* . ,sxml*))
(define (Ul #:attr* [attr* '()] . sxml*)
  `(ul ,attr* . ,sxml*))
(define (Var #:attr* [attr* '()] . sxml*)
  `(var ,attr* . ,sxml*))
(define (Video #:attr* [attr* '()] . sxml*)
  `(video ,attr* . ,sxml*))
(define (Wbr #:attr* [attr* '()] . sxml*)
  `(wbr ,attr* . ,sxml*))