#lang racket
(require SMathML)
(define (type-of var env)
  (cond ((assoc var env) => cdr)
        (else (error 'type-of "unknown variable ~s" var))))
(define (extend-env var type env)
  (cons (cons var type) env))
(define (reify t)
  (define (reify t)
    (match t
      ((-> ,t1 ,t2) (&impl (@reify t1) (@reify t2)))
      ((conj ,t1 ,t2) (&conj (@reify t1) (@reify t2)))
      ((disj ,t1 ,t2) (&disj (@reify t1) (@reify t2)))
      (bot $bottom)
      (top $top)
      (,else t)))
  (define (@reify t)
    (match t
      ((-> ,t1 ,t2) (@impl (@reify t1) (@reify t2)))
      ((conj ,t1 ,t2) (@conj (@reify t1) (@reify t2)))
      ((disj ,t1 ,t2) (@disj (@reify t1) (@reify t2)))
      (bot $bottom)
      (top $top)
      (,else t)))
  (reify t))
(struct result (t c) #:transparent)
(define (VAR u)
  (lambda (env)
    (define t (type-of u env))
    (result t (assume u (&true (reify t))))))
(define (CONS a b)
  (lambda (env)
    (match-define (result ta ca) (a env))
    (match-define (result tb cb) (b env))
    (define type `(conj ,ta ,tb))
    (result type
            (&rull $conjI ca cb
                   (&true (reify type))))))
(define (CAR a)
  (lambda (env)
    (match-define (result ta ca) (a env))
    (match ta
      ((conj ,t1 ,t2)
       (result t1 (&rull $conjE1 ca
                         (&true (reify t1))))))))
(define (CDR a)
  (lambda (env)
    (match-define (result ta ca) (a env))
    (match ta
      ((conj ,t1 ,t2)
       (result t2 (&rull $conjE2 ca
                         (&true (reify t2))))))))
(define (LAM u t body)
  (lambda (env)
    (match-define (result tbody cbody)
      (body (extend-env u t env)))
    (define type `(-> ,t ,tbody))
    (result type
            (&rull (&implI u) cbody
                   (&true (reify type))))))
(define (APP a b)
  (lambda (env)
    (match-define (result ta ca) (a env))
    (match-define (result tb cb) (b env))
    (match ta
      ((-> ,t1 ,t2)
       (unless (equal? t1 tb)
         (error 'APP "type mismatch"))
       (result t2 (&rull $implE ca cb
                         (&true (reify t2))))))))
(define (INL tb a)
  (lambda (env)
    (match-define (result ta ca) (a env))
    (define type `(disj ,ta ,tb))
    (result type (&rull $disjI1 ca
                        (&true (reify type))))))
(define (INR ta b)
  (lambda (env)
    (match-define (result tb cb) (b env))
    (define type `(disj ,ta ,tb))
    (result type (&rull $disjI2 cb
                        (&true (reify type))))))
(define (CASE a u1 b1 u2 b2)
  (lambda (env)
    (match-define (result ta ca) (a env))
    (match ta
      ((disj ,t1 ,t2)
       (match-define (result tb1 cb1)
         (b1 (extend-env u1 t1 env)))
       (match-define (result tb2 cb2)
         (b2 (extend-env u2 t2 env)))
       (unless (equal? tb1 tb2)
         (error 'CASE "branch type mismatch"))
       (result tb1 (&rull (&disjE u1 u2) ca cb1 cb2
                          (&true (reify tb1))))))))
(define (ND proof)
  (result-c (proof '())))
(define (&rule #:space [n 8] . j*)
  (let-values (((j* j1) (split-at-right j* 1)))
    (~ #:attr* '((displaystyle "true"))
       (apply (&split n) j*) (car j1))))
(define (&rull label . x*)
  (if label
      (: (apply &rule x*) label)
      (apply &rule x*)))
(define &split2 (&split 2))
(define $true
  (Mi #:attr* '((mathvariant "italic"))
      "true"))
(define (&true A)
  (&split2 A $true))
(define (assume u t)
  (&rull u t))
(define $impl $sup)
(define-infix*
  (&impl $impl))
(define-@lized-op*
  (@impl &impl))
(define $disj:id (Mi "&or;"))
(define $conj:id (Mi "&and;"))
(define $impl:id (Mi "&sup;"))
(define $disjI1 (: $disj:id $I_1))
(define $disjI2 (: $disj:id $I_2))
(define (&disjE u w)
  (: $disj:id (^ $E (&cm u w))))
(define $conjI (: $conj:id $I))
(define $conjE1 (: $conj:id $E_1))
(define $conjE2 (: $conj:id $E_2))
(define (&implI u)
  (: $impl:id (^ $I u)))
(define $implE
  (: $impl:id $E))
(define test.html
  (TmPrelude
   #:css "styles.css"
   (CodeB "(MB (ND (LAM $u `(-> (disj ,$A ,$B) ,$C)
             (CONS (LAM $w $A
                        (APP (VAR $u)
                             (INL $B (VAR $w))))
                   (LAM $x $B
                        (APP (VAR $u)
                             (INR $A (VAR $x))))))))")
   (MB (ND (LAM $u `(-> (disj ,$A ,$B) ,$C)
                (CONS (LAM $w $A
                           (APP (VAR $u)
                                (INL $B (VAR $w))))
                      (LAM $x $B
                           (APP (VAR $u)
                                (INR $A (VAR $x))))))))
   (CodeB "(MB (ND (LAM $u `(conj (-> ,$A ,$C) (-> ,$B ,$C))
             (LAM $w `(disj ,$A ,$B)
                  (CASE (VAR $w)
                        $x (APP (CAR (VAR $u)) (VAR $x))
                        $y (APP (CDR (VAR $u)) (VAR $y)))))))")
   (MB (ND (LAM $u `(conj (-> ,$A ,$C) (-> ,$B ,$C))
                (LAM $w `(disj ,$A ,$B)
                     (CASE (VAR $w)
                           $x (APP (CAR (VAR $u)) (VAR $x))
                           $y (APP (CDR (VAR $u)) (VAR $y)))))))
   (CodeB "(let ((Neg (lambda (A) `(-> ,A bot))))
  (MB (ND (LAM $u (Neg `(disj ,$A ,(Neg $A)))
               (APP (LAM $v (Neg $A)
                         (APP (VAR $u)
                              (INR $A (VAR $v))))
                    (LAM $w $A
                         (APP (VAR $u)
                              (INL (Neg $A) (VAR $w)))))))))")
   (let ((Neg (lambda (A) `(-> ,A bot))))
     (MB (ND (LAM $u (Neg `(disj ,$A ,(Neg $A)))
                  (APP (LAM $v (Neg $A)
                            (APP (VAR $u)
                                 (INR $A (VAR $v))))
                       (LAM $w $A
                            (APP (VAR $u)
                                 (INL (Neg $A) (VAR $w)))))))))
   ))
(parameterize ([replace? #t])
  (emitXml test.html "test.html"))
