#lang racket
(require "match.rkt")
;<lang> ::= 0
;        |  1
;        |  <symbol>
;        |  (* <lang>)
;        |  (U <lang> <lang>)
;        |  (o <lang> <lang>)
(define (* L)
  (cond ((eqv? L 0) 0)
        ((eqv? L 1) 1)
        (else `(* ,L))))
(define (U L1 L2)
  (cond ((eqv? L1 0) L2)
        ((eqv? L2 0) L1)
        (else `(U ,L1 ,L2))))
(define (o L1 L2)
  (cond ((eqv? L1 0) 0)
        ((eqv? L1 1) L2)
        ((eqv? L2 0) 0)
        ((eqv? L2 1) L1)
        (else `(o ,L1 ,L2))))
(define (delta? L)
  (match L
    (0 #f)
    (1 #t)
    (,c (guard (symbol? c)) #f)
    ((* ,L) #t)
    ((U ,L1 ,L2)
     (or (delta? L1) (delta? L2)))
    ((o ,L1 ,L2)
     (and (delta? L1) (delta? L2)))))
(define (empty? L)
  (match L
    (0 #t)
    (1 #f)
    (,c (guard (symbol? c)) #f)
    ((* ,L) (empty? L))
    ((U ,L1 ,L2) (and (empty? L1) (empty? L2)))
    ((o ,L1 ,L2) (or (empty? L1) (empty? L2)))))
(define (D c L)
  (match L
    (0 0)
    (1 0)
    (,a (guard (symbol? a)) (if (eq? c a) 1 0))
    ((* ,L) (o (D c L) (* L)))
    ((U ,L1 ,L2) (U (D c L1) (D c L2)))
    ((o ,L1 ,L2)
     (if (delta? L1)
         (U (o (D c L1) L2) (D c L2))
         (o (D c L1) L2)))))
(define (matches? w L)
  (cond ((null? w) (delta? L))
        ((empty? L) #f)
        (else
         (matches? (cdr w) (D (car w) L)))))