#lang racket
(provide (all-defined-out))
(require "utils.rkt")
;<term> ::= <var> | (<func> <term>*)
;<predicate> ::= (<pred> <term>*)
;<exp> ::= <bool>
;       |  <predicate>
;       |  (not <exp>)
;       |  (and <exp> <exp>)
;       |  (or <exp> <exp>)
;       |  (=> <exp> <exp>)
;       |  (<=> <exp> <exp>)
;       |  (forall <var> <exp>)
;       |  (exists <var> <exp>)
(struct interp (domain func pred))
(define (funcval m f)
  ((interp-func m) f))
(define (predval m p)
  ((interp-pred m) p))
(define ((termval m v) term)
  (match term
    (,x (guard (symbol? x)) (v x))
    ((,func . ,term*)
     (apply (funcval m func)
            (map (termval m v) term*)))))
(define (holds? m v exp)
  (match exp
    (,b (guard (boolean? b)) b)
    ((not ,e) (not (holds? m v e)))
    ((and ,e1 ,e2) (and (holds? m v e1)
                        (holds? m v e2)))
    ((or ,e1 ,e2) (or (holds? m v e1)
                      (holds? m v e2)))
    ((=> ,e1 ,e2) (or (not (holds? m v e1))
                      (holds? m v e2)))
    ((<=> ,e1 ,e2) (eq? (holds? m v e1)
                        (holds? m v e2)))
    ((forall ,x ,e)
     (forall? (lambda (a)
                (holds? m (extend v x a) e))
              (interp-domain m)))
    ((exists ,x ,e)
     (exists? (lambda (a)
                (holds? m (extend v x a) e))
              (interp-domain m)))
    ((,pred . ,term*)
     (apply (predval m pred)
            (map (termval m v) term*)))))
(define boole
  (interp '(#f #t)
          (lambda (f)
            (case f
              ((zero) (lambda () #f))
              ((one) (lambda () #t))
              ;exclusive or
              ((+) (lambda (a b)
                     (not (eq? a b))))
              ((*) (lambda (a b)
                     (and a b)))
              (else (error 'boole "unknown func symbol ~s" f))))
          (lambda (p)
            (case p
              ((=) (lambda (a b)
                     (eq? a b)))
              (else (error 'boole "unknown pred symbol ~s" p))))))
(define (mod-interp n)
  (interp (range n)
          (lambda (f)
            (case f
              ((zero) (lambda () 0))
              ((one) (lambda () (modulo 1 n)))
              ((+) (lambda (a b)
                     (modulo (+ a b) n)))
              ((*) (lambda (a b)
                     (modulo (* a b) n)))
              (else (error 'mod-interp "unknown func symbol ~s" f))))
          (lambda (p)
            (case p
              ((=) (lambda (a b) (= a b)))
              (else (error 'mod-interp "unknown pred symbol ~s" p))))))
(define modulo_inverse_existence
  '(forall x (=> (not (= x (zero)))
                 (exists y (= (* x y) (one))))))
#;
(filter (lambda (n)
          (holds? (mod-interp n) undefined
                  modulo_inverse_existence))
        (range 1 100))
(define (fvt term)
  (match term
    (,x (guard (symbol? x)) (list x))
    ((,func . ,term*)
     (apply U* (map fvt term*)))))
(define (fv exp)
  (match exp
    (,b (guard (boolean? b)) '())
    ((not ,e) (fv e))
    ((,op ,e1 ,e2)
     (guard (connective2? op))
     (U (fv e1) (fv e2)))
    ((,q ,x ,e)
     (guard (quantifier? q))
     (D (fv e) (list x)))
    ((,pred . ,term*)
     (apply U* (map fvt term*)))))
(define (generalize exp)
  (fold-left
   (lambda (exp var)
     `(forall ,var ,exp))
   exp (fv exp)))
(define ((tsubst i) term)
  (match term
    (,x (guard (symbol? x)) (i x))
    ((,func . ,term*)
     `(,func . ,(map (tsubst i) term*)))))
(define (subst i exp)
  (match exp
    (,b (guard (boolean? b)) b)
    ((not ,e) `(not ,(subst i e)))
    ((,op ,e1 ,e2)
     (guard (connective2? op))
     `(,op ,(subst i e1) ,(subst i e2)))
    ((,q ,x ,e)
     (guard (quantifier? q))
     (qsubst i q x e))
    ((,pred . ,term*)
     `(,pred . ,(map (tsubst i) term*)))))
#;
(define (qsubst i q x e)
  (define x^ (gensym x))
  `(,q ,x^ ,(subst (extend i x x^) e)))
#;
(define (qsubst i q x e)
  (define (capture?)
    (exists?
     (lambda (y)
       (memq x (fvt (i y))))
     (D (fv e) (list x))))
  (define x^
    (if (capture?)
        (gensym x)
        x))
  `(,q ,x^ ,(subst (extend i x x^) e)))
(define (qsubst i q x e)
  (define (capture?)
    (exists?
     (lambda (y)
       (memq x (fvt (i y))))
     (D (fv e) (list x))))
  (define x^
    (if (capture?)
        (variant x (fv (subst (undefine i x) e)))
        x))
  `(,q ,x^ ,(subst (extend i x x^) e)))
(define (Quant q x e)
  (if (memq x (fv e))
      `(,q ,x ,e)
      e))
(define (simplify exp)
  (define (simp exp)
    (match exp
      ((not ,e1) (Not (simp e1)))
      ((and ,e1 ,e2) (And (simp e1) (simp e2)))
      ((or ,e1 ,e2) (Or (simp e1) (simp e2)))
      ((=> ,e1 ,e2) (Imp (simp e1) (simp e2)))
      ((<=> ,e1 ,e2) (Iff (simp e1) (simp e2)))
      ((,q ,x ,e)
       (guard (quantifier? q))
       (Quant q x (simp e)))
      (,else exp)))
  (simp exp))
(define (nnf exp)
  (define (Not exp)
    (match exp
      ((not ,e1) (nnf e1))
      ((and ,e1 ,e2)
       `(or ,(Not e1) ,(Not e2)))
      ((or ,e1 ,e2)
       `(and ,(Not e1) ,(Not e2)))
      ((=> ,e1 ,e2)
       `(and ,(nnf e1) ,(Not e2)))
      ((<=> ,e1 ,e2)
       `(or (and ,(nnf e1) ,(Not e2))
            (and ,(Not e1) ,(nnf e2))))
      ((forall ,x ,e)
       `(exists ,x ,(Not e)))
      ((exists ,x ,e)
       `(forall ,x ,(Not e)))
      (,else `(not ,exp))))
  (define (nnf exp)
    (match exp
      ((not ,e1) (Not e1))
      ((and ,e1 ,e2) `(and ,(nnf e1) ,(nnf e2)))
      ((or ,e1 ,e2) `(or ,(nnf e1) ,(nnf e2)))
      ((=> ,e1 ,e2) `(or ,(Not e1) ,(nnf e2)))
      ((<=> ,e1 ,e2)
       `(or (and ,(nnf e1) ,(nnf e2))
            (and ,(Not e1) ,(Not e2))))
      ((forall ,x ,e) `(forall ,x ,(nnf e)))
      ((exists ,x ,e) `(exists ,x ,(nnf e)))
      (,else exp)))
  (nnf (simplify exp)))
(define (pullquants exp)
  (define (rename flag x z e)
    (if (and flag (not (eq? x z)))
        (subst (\|=> x z) e)
        e))
  (define (pullq lf rf exp quant op x y p q)
    (define z (variant x (fv exp)))
    (define p^ (rename lf x z p))
    (define q^ (rename rf y z q))
    `(,quant ,z ,(pullquants `(,op ,p^ ,q^))))
  (define (pullquants exp)
    (match exp
      ((and (forall ,x ,p) (forall ,y ,q))
       (pullq #t #t exp 'forall 'and x y p q))
      ((or (exists ,x ,p) (exists ,y ,q))
       (pullq #t #t exp 'exists 'or x y p q))
      ((,op (,quant ,x ,p) ,q)
       (guard (quantifier? quant))
       (pullq #t #f exp quant op x x p q))
      ((,op ,p (,quant ,y ,q))
       (guard (quantifier? quant))
       (pullq #f #t exp quant op y y p q))
      (,else exp)))
  (pullquants exp))
(define (prenex exp)
  (match exp
    ((,q ,x ,e)
     (guard (quantifier? q))
     `(,q ,x ,(prenex e)))
    ((,op ,p ,q)
     (guard (memq op '(and or)))
     (pullquants `(,op ,(prenex p) ,(prenex q))))
    (,else exp)))
(define (pnf exp)
  (prenex (nnf exp)))
(define (funcs term)
  (match term
    (,var (guard (symbol? var)) '())
    ((,func . ,term*)
     (set-cons (list func (length term*))
               (funcs* term*)))))
(define (funcs* term*)
  (apply U* (map funcs term*)))
(define (functions exp)
  (match exp
    (,b (guard (boolean? b)) '())
    ((not ,e) (functions e))
    ((,op ,e1 ,e2)
     (guard (connective2? op))
     (U (functions e1) (functions e2)))
    ((,q ,x ,e)
     (guard (quantifier? q))
     (functions e))
    ((,pred . ,term*) (funcs* term*))))
(define (predicates exp)
  (match exp
    (,b (guard (boolean? b)) '())
    ((not ,e) (predicates e))
    ((,op ,e1 ,e2)
     (guard (connective2? op))
     (U (predicates e1) (predicates e2)))
    ((,q ,x ,e)
     (guard (quantifier? q))
     (predicates e))
    ((,pred . ,term*)
     (list (list pred (length term*))))))
(define ((make-sym x) n)
  (string->symbol
   (format "~a~a" x n)))
(define (function-congruence f n)
  (if (= n 0)
      '()
      (let* ((x* (map (make-sym 'x) (range n)))
             (y* (map (make-sym 'y) (range n)))
             (ant (make-conj
                   (map (lambda (x y) `(= ,x ,y))
                        x* y*)))
             (con `(= (,f . ,x*) (,f . ,y*))))
        (list (fold-right
               (lambda (a d)
                 `(forall ,a ,d))
               `(=> ,ant ,con)
               (append x* y*))))))
(define (predicate-congruence p n)
  (if (= n 0)
      '()
      (let* ((x* (map (make-sym 'x) (range n)))
             (y* (map (make-sym 'y) (range n)))
             (ant (make-conj
                   (map (lambda (x y) `(= ,x ,y))
                        x* y*)))
             (con `(=> (,p . ,x*) (,p . ,y*))))
        (list (fold-right
               (lambda (a d)
                 `(forall ,a ,d))
               `(=> ,ant ,con)
               (append x* y*))))))
(define equivalence-axioms
  '((forall x (= x x))
    (forall
     x (forall
        y (forall
           z (=> (and (= x y) (= x z))
                 (= y z)))))))
(define (equalitize exp)
  (define allpreds (predicates exp))
  (if (member (list '= 2) allpreds)
      (let* ((axioms (append
                      (append-map
                       (curry apply function-congruence)
                       (functions exp))
                      (append-map
                       (curry apply predicate-congruence)
                       (remove (list '= 2) allpreds))
                      equivalence-axioms)))
        `(=> ,(make-conj axioms) ,exp))
      exp))
(define (specialize exp)
  (match exp
    ((forall ,x ,e) (specialize e))
    (,else exp)))
(define (askolemize exp)
  (define (skolem exp f*)
    (match exp
      ((exists ,y ,p)
       (define x* (fv exp))
       (define f
         (variant (if (null? x*)
                      (symbol-append 'c_ y)
                      (symbol-append 'f_ y))
                  f*))
       (skolem (subst (\|=> y (cons f x*)) p)
               (cons f f*)))
      ((forall ,x ,p)
       (let-values (((p f*) (skolem p f*)))
         (values `(forall ,x ,p) f*)))
      ((,op ,p ,q)
       (guard (memq op '(and or)))
       (skolem2 op p q f*))
      (,else (values exp f*))))
  (define (skolem2 op p q f*)
    (let*-values (((p f*) (skolem p f*))
                  ((q f*) (skolem q f*)))
      (values `(,op ,p ,q) f*)))
  (let-values (((exp f*)
                (skolem (nnf exp)
                        (image car (functions exp)))))
    exp))
(define (skolemize exp)
  (specialize (prenex (askolemize exp))))
(define (ev e v)
  (match e
    (,b (guard (boolean? b)) b)
    ((not ,e1) (not (ev e1 v)))
    ((and ,e1 ,e2) (and (ev e1 v) (ev e2 v)))
    ((or ,e1 ,e2) (or (ev e1 v) (ev e2 v)))
    ((=> ,e1 ,e2) (or (not (ev e1 v)) (ev e2 v)))
    ((<=> ,e1 ,e2) (eq? (ev e1 v) (ev e2 v)))
    ((,q ,x ,e)
     (guard (quantifier? q))
     (error 'ev "ev only accepts quantifier-free formulas"))
    ((,pred . ,term*) (v e))))
(define (pholds? d e) (ev e d))
