#lang racket
(require "utils.rkt")
;<term> ::= <var> | (<func> <term>*)
;<predicate> ::= (<pred> <term>*)
;<exp> ::= <bool>
;       |  <predicate>
;       |  (not <exp>)
;       |  (and <exp> <exp>)
;       |  (or <exp> <exp>)
;       |  (=> <exp> <exp>)
;       |  (<=> <exp> <exp>)
;       |  (forall <var> <exp>)
;       |  (exists <var> <exp>)
(struct interp (domain func pred))
(define ((termval m v) term)
  (match term
    (,x (guard (symbol? x)) (v x))
    ((,func . ,term*)
     (apply (funcval m func)
            (map (termval m v) term*)))))
(define (funcval m f)
  ((interp-func m) f))
(define (predval m p)
  ((interp-pred m) p))
(define (extend v x a)
  (lambda (y)
    (if (eq? y x)
        a
        (v y))))
(define (holds? m v exp)
  (match exp
    (,b (guard (boolean? b)) b)
    ((not ,e) (not (holds? m v e)))
    ((and ,e1 ,e2) (and (holds? m v e1)
                        (holds? m v e2)))
    ((or ,e1 ,e2) (or (holds? m v e1)
                      (holds? m v e2)))
    ((=> ,e1 ,e2) (or (not (holds? m v e1))
                      (holds? m v e2)))
    ((<=> ,e1 ,e2) (eq? (holds? m v e1)
                        (holds? m v e2)))
    ((forall ,x ,e)
     (forall? (lambda (a)
                (holds? m (extend v x a) e))
              (interp-domain m)))
    ((exists ,x ,e)
     (exists? (lambda (a)
                (holds? m (extend v x a) e))
              (interp-domain m)))
    ((,pred . ,term*)
     (apply (predval m pred)
            (map (termval m v) term*)))))
(define boole
  (interp '(#f #t)
          (lambda (f)
            (case f
              ((zero) (lambda () #f))
              ((one) (lambda () #t))
              ;exclusive or
              ((+) (lambda (a b)
                     (not (eq? a b))))
              ((*) (lambda (a b)
                     (and a b)))
              (else (error 'boole "unknown func symbol ~s" f))))
          (lambda (p)
            (case p
              ((=) (lambda (a b)
                     (eq? a b)))
              (else (error 'boole "unknown pred symbol ~s" p))))))
(define (mod-interp n)
  (interp (range n)
          (lambda (f)
            (case f
              ((zero) (lambda () 0))
              ((one) (lambda () (modulo 1 n)))
              ((+) (lambda (a b)
                     (modulo (+ a b) n)))
              ((*) (lambda (a b)
                     (modulo (* a b) n)))
              (else (error 'mod-interp "unknown func symbol ~s" f))))
          (lambda (p)
            (case p
              ((=) (lambda (a b) (= a b)))
              (else (error 'mod-interp "unknown pred symbol ~s" p))))))
(define modulo_inverse_existence
  '(forall x (=> (not (= x (zero)))
                 (exists y (= (* x y) (one))))))
#;
(filter (lambda (n)
          (holds? (mod-interp n) undefined
                  modulo_inverse_existence))
        (range 1 100))
(define (fvt term)
  (match term
    (,x (guard (symbol? x)) (list x))
    ((,func . ,term*)
     (apply U* (map fvt term*)))))
(define (fv exp)
  (match exp
    (,b (guard (boolean? b)) '())
    ((not ,e) (fv e))
    ((,op ,e1 ,e2)
     (guard (memq op '(and or => <=>)))
     (U (fv e1) (fv e2)))
    ((,q ,x ,e)
     (guard (memq q '(forall exists)))
     (D (fv e) (list x)))
    ((,pred . ,term*)
     (apply U* (map fvt term*)))))
(define (generalize exp)
  (fold-left
   (lambda (exp var)
     `(forall ,var ,exp))
   exp (fv exp)))
