#lang racket
(provide (except-out (all-defined-out) ppat))
(define-syntax match
  (syntax-rules (guard)
    ((_ v) (error 'match "~s" v))
    ((_ v (pat (guard g ...) e ...) cs ...)
     (let ((fk (lambda () (match v cs ...))))
       (ppat v pat (if (and g ...) (let () e ...) (fk)) (fk))))
    ((_ v (pat e ...) cs ...)
     (let ((fk (lambda () (match v cs ...))))
       (ppat v pat (let () e ...) (fk))))))
(define-syntax ppat
  (syntax-rules (unquote)
    ((_ v () kt kf) (if (null? v) kt kf))
    ((_ v (unquote var) kt kf) (let ((var v)) kt))
    ((_ v (x . y) kt kf)
     (if (pair? v)
         (let ((vx (car v)) (vy (cdr v)))
           (ppat vx x (ppat vy y kt kf) kf))
         kf))
    ((_ v lit kt kf) (if (eqv? v (quote lit)) kt kf))))
(define (forall? pred lst)
  (cond ((null? lst) #t)
        ((pred (car lst))
         (forall? pred (cdr lst)))
        (else #f)))
(define (exists? pred lst)
  (cond ((null? lst) #f)
        ((pred (car lst)) #t)
        (else
         (exists? pred (cdr lst)))))
(define (fold-left proc init lst)
  (if (null? lst)
      init
      (fold-left proc (proc init (car lst)) (cdr lst))))
(define (remove-all x lst)
  (cond ((null? lst) '())
        ((equal? x (car lst))
         (remove-all x (cdr lst)))
        (else
         (cons (car lst) (remove-all x (cdr lst))))))
;set operations
(define (set-cons x s)
  (if (member x s)
      s
      (cons x s)))
(define (setlize x*)
  (if (null? x*)
      '()
      (set-cons (car x*)
                (setlize (cdr x*)))))
(define (U s1 s2)
  (cond ((null? s1) s2)
        ((member (car s1) s2) (U (cdr s1) s2))
        (else (cons (car s1) (U (cdr s1) s2)))))
(define U*
  (case-lambda
    (() '())
    ((s) s)
    ((s1 s2 . s*) (apply U* (U s1 s2) s*))))
(define (D s1 s2)
  (cond ((null? s1) '())
        ((member (car s1) s2) (D (cdr s1) s2))
        (else (cons (car s1) (D (cdr s1) s2)))))
(define (I? s1 s2)
  (cond ((null? s1) #f)
        ((member (car s1) s2) #t)
        (else (I? (cdr s1) s2))))
(define (subset? s1 s2)
  (cond ((null? s1) #t)
        ((member (car s1) s2)
         (subset? (cdr s1) s2))
        (else #f)))
(define (make-conj x*)
  (cond ((null? x*) #t)
        ((null? (cdr x*)) (car x*))
        (else
         (let rec ((x (car x*))
                   (x* (cdr x*)))
           (if (null? x*)
               x
               `(and ,x ,(rec (car x*) (cdr x*))))))))
(define (make-disj x*)
  (cond ((null? x*) #f)
        ((null? (cdr x*)) (car x*))
        (else
         (let rec ((x (car x*))
                   (x* (cdr x*)))
           (if (null? x*)
               x
               `(or ,x ,(rec (car x*) (cdr x*))))))))
(define (allpairs f x* y*)
  (append-map
   (lambda (y)
     (map (lambda (x) (f x y)) x*))
   y*))
(define undefined
  (lambda (x)
    (error 'undefined "unknown variable ~s" x)))