#lang racket
(provide (except-out (all-defined-out) ppat))
(define-syntax match
  (syntax-rules (guard)
    ((_ v) (error 'match "~s" v))
    ((_ v (pat (guard g ...) e ...) cs ...)
     (let ((fk (lambda () (match v cs ...))))
       (ppat v pat (if (and g ...) (let () e ...) (fk)) (fk))))
    ((_ v (pat e ...) cs ...)
     (let ((fk (lambda () (match v cs ...))))
       (ppat v pat (let () e ...) (fk))))))
(define-syntax ppat
  (syntax-rules (unquote)
    ((_ v () kt kf) (if (null? v) kt kf))
    ((_ v (unquote var) kt kf) (let ((var v)) kt))
    ((_ v (x . y) kt kf)
     (if (pair? v)
         (let ((vx (car v)) (vy (cdr v)))
           (ppat vx x (ppat vy y kt kf) kf))
         kf))
    ((_ v lit kt kf) (if (eqv? v (quote lit)) kt kf))))
(define (forall? pred lst)
  (cond ((null? lst) #t)
        ((pred (car lst))
         (forall? pred (cdr lst)))
        (else #f)))
(define (exists? pred lst)
  (cond ((null? lst) #f)
        ((pred (car lst)) #t)
        (else
         (exists? pred (cdr lst)))))
(define (fold-left proc init lst)
  (if (null? lst)
      init
      (fold-left proc (proc init (car lst)) (cdr lst))))
(define (fold-right proc init lst)
  (if (null? lst)
      init
      (proc (car lst)
            (fold-right proc init (cdr lst)))))
(define (remove-all x lst)
  (cond ((null? lst) '())
        ((equal? x (car lst))
         (remove-all x (cdr lst)))
        (else
         (cons (car lst) (remove-all x (cdr lst))))))
;set operations
(define (set-cons x s)
  (if (member x s)
      s
      (cons x s)))
(define (setlize x*)
  (if (null? x*)
      '()
      (set-cons (car x*)
                (setlize (cdr x*)))))
(define (image f x*)
  (setlize (map f x*)))
(define (U s1 s2)
  (cond ((null? s1) s2)
        ((member (car s1) s2) (U (cdr s1) s2))
        (else (cons (car s1) (U (cdr s1) s2)))))
(define U*
  (case-lambda
    (() '())
    ((s) s)
    ((s1 s2 . s*) (apply U* (U s1 s2) s*))))
(define (D s1 s2)
  (cond ((null? s1) '())
        ((member (car s1) s2) (D (cdr s1) s2))
        (else (cons (car s1) (D (cdr s1) s2)))))
(define (I? s1 s2)
  (cond ((null? s1) #f)
        ((member (car s1) s2) #t)
        (else (I? (cdr s1) s2))))
(define (subset? s1 s2)
  (cond ((null? s1) #t)
        ((member (car s1) s2)
         (subset? (cdr s1) s2))
        (else #f)))
(define (make-conj x*)
  (cond ((null? x*) #t)
        ((null? (cdr x*)) (car x*))
        (else
         (let rec ((x (car x*))
                   (x* (cdr x*)))
           (if (null? x*)
               x
               `(and ,x ,(rec (car x*) (cdr x*))))))))
(define (make-disj x*)
  (cond ((null? x*) #f)
        ((null? (cdr x*)) (car x*))
        (else
         (let rec ((x (car x*))
                   (x* (cdr x*)))
           (if (null? x*)
               x
               `(or ,x ,(rec (car x*) (cdr x*))))))))
(define (allpairs f x* y*)
  (append-map
   (lambda (y)
     (map (lambda (x) (f x y)) x*))
   y*))
(define undefined
  (lambda (x)
    (error 'undefined "unknown variable ~s" x)))
(define (extend v x a)
  (lambda (y)
    (if (eq? y x)
        a
        (v y))))
(define (undefine v x)
  (extend v x x))
(define (\|=> x y)
  (lambda (z)
    (if (eq? z x) y z)))
(define (Not exp)
  (match exp
    (,b (guard (boolean? b)) (not b))
    ((not ,e1) e1)
    (,else `(not ,exp))))
(define (And e1 e2)
  (cond ((eq? e1 #f) #f)
        ((eq? e2 #f) #f)
        ((eq? e1 #t) e2)
        ((eq? e2 #t) e1)
        (else `(and ,e1 ,e2))))
(define (Or e1 e2)
  (cond ((eq? e1 #t) #t)
        ((eq? e2 #t) #t)
        ((eq? e1 #f) e2)
        ((eq? e2 #f) e1)
        (else `(or ,e1 ,e2))))
(define (Imp e1 e2)
  (cond ((eq? e1 #f) #t)
        ((eq? e2 #t) #t)
        ((eq? e1 #t) e2)
        ((eq? e2 #f) (Not e1))
        (else `(=> ,e1 ,e2))))
(define (Iff e1 e2)
  (cond ((eq? e1 #t) e2)
        ((eq? e2 #t) e1)
        ((eq? e1 #f) (Not e2))
        ((eq? e2 #f) (Not e1))
        (else `(<=> ,e1 ,e2))))
(define (quantifier? x)
  (memq x '(forall exists)))
(define (connective2? x)
  (memq x '(and or => <=>)))
(define (attach^ x)
  (string->symbol
   (format "~a^" x)))
(define (variant x x*)
  (if (memq x x*)
      (variant (attach^ x) x*)
      x))
;gensym produces an uninterned symbol.
;In principle, you should not copy-and-paste
;the output of procedures which use fresh-var
;as the input of other procedures.
(define (fresh-var)
  (gensym 'p_))
(define (symbol-append . x*)
  (string->symbol
   (apply string-append
          (map symbol->string x*))))
